apiVersion: v1
kind: Namespace
metadata:
  name: ex2
  labels:
    name: ex2

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-app
  namespace: ex2
  labels:
    name: weather-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: weather
  template:
    metadata:
      labels:
        app: weather
    spec:
      containers:
      - name: weather-cont
        image: caroozy/jenkins-weather:132
        ports:
          - containerPort: 8989

---

apiVersion: v1
kind: Service
metadata:
  name: weather-app
  namespace: ex2
spec:
  type: NodePort
  selector:
    app: weather
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8989
